[tools]
node = "20.13.1"
go = "1.22.3"
bun = "1.1.8"
python = "3.12.3"
neovim = "0.10.0"
kubectl = "1.30.1"
helm = "3.15.0"
minikube = "1.33.1"
awscli = "2.15.53"
lua = "5.4.6"
ocaml = "5.2.0"
opam = "2.1.6"
zig = "master"
ghc = "9.8.2"
cabal = "3.10.3.0"
hls = "2.8.0.0"
stack = "2.15.7"
haskell = "9.8.2"
